# Generated by Django 4.2 on 2023-12-22 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0002_order_tax_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modifier_type', models.CharField(choices=[('D', 'Discount'), ('T', 'Tax')], max_length=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_app.order')),
            ],
        ),
        migrations.RemoveField(
            model_name='tax',
            name='order',
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
